add_test( checkRotateTest.CheckRoateTest /home/hyq/MiniOB/buld/bin/log_test [==[--gtest_filter=checkRotateTest.CheckRoateTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( checkRotateTest.CheckRoateTest PROPERTIES WORKING_DIRECTORY /home/hyq/MiniOB/buld/unittest)
add_test( testEnableTest.CheckEnableTest /home/hyq/MiniOB/buld/bin/log_test [==[--gtest_filter=testEnableTest.CheckEnableTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( testEnableTest.CheckEnableTest PROPERTIES WORKING_DIRECTORY /home/hyq/MiniOB/buld/unittest)
set( log_test_TESTS checkRotateTest.CheckRoateTest testEnableTest.CheckEnableTest)
