if(EXISTS "/home/hyq/MiniOB/buld/unittest/persist_test[1]_tests.cmake")
  include("/home/hyq/MiniOB/buld/unittest/persist_test[1]_tests.cmake")
else()
  add_test(persist_test_NOT_BUILT persist_test_NOT_BUILT)
endif()
