add_test( [==[Expected equality of these values:.pid]==] /home/hyq/MiniOB/buld/bin/pidfile_test [==[--gtest_filter=Expected equality of these values:.pid]==] --gtest_also_run_disabled_tests)
set_tests_properties( [==[Expected equality of these values:.pid]==] PROPERTIES WORKING_DIRECTORY /home/hyq/MiniOB/buld/unittest)
add_test( [==[Expected equality of these values:.Whichis:7178]==] /home/hyq/MiniOB/buld/bin/pidfile_test [==[--gtest_filter=Expected equality of these values:.Whichis:7178]==] --gtest_also_run_disabled_tests)
set_tests_properties( [==[Expected equality of these values:.Whichis:7178]==] PROPERTIES WORKING_DIRECTORY /home/hyq/MiniOB/buld/unittest)
add_test( [==[Expected equality of these values:.target]==] /home/hyq/MiniOB/buld/bin/pidfile_test [==[--gtest_filter=Expected equality of these values:.target]==] --gtest_also_run_disabled_tests)
set_tests_properties( [==[Expected equality of these values:.target]==] PROPERTIES WORKING_DIRECTORY /home/hyq/MiniOB/buld/unittest)
add_test( [==[Expected equality of these values:.Whichis:3200]==] /home/hyq/MiniOB/buld/bin/pidfile_test [==[--gtest_filter=Expected equality of these values:.Whichis:3200]==] --gtest_also_run_disabled_tests)
set_tests_properties( [==[Expected equality of these values:.Whichis:3200]==] PROPERTIES WORKING_DIRECTORY /home/hyq/MiniOB/buld/unittest)
set( pidfile_test_TESTS [==[Expected equality of these values:.pid]==] [==[Expected equality of these values:.Whichis:7178]==] [==[Expected equality of these values:.target]==] [==[Expected equality of these values:.Whichis:3200]==])
